# Generated by Django 5.1.3 on 2024-12-06 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=None, max_length=50)),
                ('price', models.CharField(blank=None, max_length=50)),
                ('image', models.ImageField(blank=None, max_length=500, upload_to='image')),
            ],
        ),
    ]
