# Generated by Django 5.1.3 on 2024-12-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(blank=None, max_length=150)),
            ],
        ),
    ]
