# Generated by Django 5.1.3 on 2024-12-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kafei', '0002_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookingform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=None, max_length=50)),
                ('phone', models.CharField(blank=None, max_length=100)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('no_of_person', models.CharField(blank=None, max_length=20)),
                ('msg', models.TextField(blank=True, max_length=150)),
            ],
        ),
    ]
